"""
Retrain the risk model on features generated by build_feature_vector.
Generates synthetic training data using the rule engine as ground truth.
"""
import sys, os, json, warnings
warnings.filterwarnings("ignore")

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
os.environ["HEALTH_PROJECT_DIR"] = os.path.dirname(__file__)

import numpy as np
import pandas as pd
import joblib
from pathlib import Path
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

import hackthathon as h

BACKEND_DIR = Path(__file__).parent
MODEL_PATH   = BACKEND_DIR / "risk_model.pkl"
ENCODER_PATH = BACKEND_DIR / "label_encoder.pkl"
SCHEMA_PATH  = BACKEND_DIR / "feature_schema.json"

print("Generating synthetic training data...")

REFERENCE = h.REFERENCE

def random_normal_labs():
    """Generate a patient with mostly normal labs."""
    labs = {}
    for key, (low, high) in REFERENCE.items():
        mid = (low + high) / 2
        spread = (high - low) / 2
        labs[key] = round(float(np.random.normal(mid, spread * 0.3)), 2)
        labs[key] = max(low * 0.5, min(high * 1.5, labs[key]))
    return labs

def random_abnormal_labs(severity="moderate"):
    """Generate a patient with abnormal labs."""
    labs = random_normal_labs()
    n_abnormal = {"mild": 2, "moderate": 5, "severe": 9, "critical": 14}[severity]
    keys = list(REFERENCE.keys())
    chosen = np.random.choice(keys, size=min(n_abnormal, len(keys)), replace=False)
    for key in chosen:
        low, high = REFERENCE[key]
        direction = np.random.choice(["high", "low"])
        if direction == "high":
            labs[key] = round(float(high * np.random.uniform(1.2, 2.5)), 2)
        else:
            labs[key] = round(float(low * np.random.uniform(0.2, 0.8)), 2)
    return labs

def labs_to_risk_label(labs: dict) -> str:
    rule = h.compute_rule_score(labs, "")
    score = rule["score"]
    if score < 20:
        return "LOW"
    elif score < 45:
        return "MODERATE"
    elif score < 70:
        return "HIGH"
    else:
        return "CRITICAL"

rows = []
labels = []

np.random.seed(42)

# Generate 2000 synthetic patients
for _ in range(600):
    labs = random_normal_labs()
    label = labs_to_risk_label(labs)
    fvec = h.build_feature_vector(labs)
    rows.append(fvec.iloc[0].to_dict())
    labels.append(label)

for _ in range(500):
    labs = random_abnormal_labs("mild")
    label = labs_to_risk_label(labs)
    fvec = h.build_feature_vector(labs)
    rows.append(fvec.iloc[0].to_dict())
    labels.append(label)

for _ in range(500):
    labs = random_abnormal_labs("moderate")
    label = labs_to_risk_label(labs)
    fvec = h.build_feature_vector(labs)
    rows.append(fvec.iloc[0].to_dict())
    labels.append(label)

for _ in range(250):
    labs = random_abnormal_labs("severe")
    label = labs_to_risk_label(labs)
    fvec = h.build_feature_vector(labs)
    rows.append(fvec.iloc[0].to_dict())
    labels.append(label)

for _ in range(150):
    labs = random_abnormal_labs("critical")
    label = labs_to_risk_label(labs)
    fvec = h.build_feature_vector(labs)
    rows.append(fvec.iloc[0].to_dict())
    labels.append(label)

df = pd.DataFrame(rows).fillna(0).astype(float)
df = df.reindex(sorted(df.columns), axis=1)

print(f"Dataset: {len(df)} samples x {len(df.columns)} features")
print(f"Label distribution: {pd.Series(labels).value_counts().to_dict()}")

# Encode labels
le = LabelEncoder()
y = le.fit_transform(labels)
print(f"Classes: {list(le.classes_)}")

# Save schema
feature_cols = list(df.columns)
with open(SCHEMA_PATH, "w") as f:
    json.dump(feature_cols, f)
print(f"Feature schema saved: {len(feature_cols)} features")

# Train
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=42, stratify=y)

model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="mlogloss",
    random_state=42,
    n_jobs=-1,
)

print("Training XGBClassifier...")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))

# Save
joblib.dump(model, MODEL_PATH)
joblib.dump(le, ENCODER_PATH)

# Also save to models/ subfolder
models_dir = BACKEND_DIR / "models"
models_dir.mkdir(exist_ok=True)
joblib.dump(model, models_dir / "risk_model.pkl")
joblib.dump(le, models_dir / "label_encoder.pkl")
with open(models_dir / "feature_schema.json", "w") as f:
    json.dump(feature_cols, f)

print(f"\nModel saved to {MODEL_PATH}")
print(f"Encoder saved to {ENCODER_PATH}")
print(f"Schema saved to {SCHEMA_PATH}")
print("\nDone!")
